Pages/Module/Announcement/Index.cshtml.cs
using HR_WorkFlow.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HR_WorkFlow.Pages.Module.Announcement
{
    [Authorize]
    public class IndexModel : PageModel
    {
        [BindProperty]
        public string? Username { get; set; }   //前端欄位綁定

        [BindProperty]
        public string? Password { get; set; }

        [BindProperty]
        public IFormFile? ImportedFile { get; set; }

        private readonly ILogger<IndexModel> _logger;
        private readonly Excel _excel;

        public IndexModel(ILogger<IndexModel> logger, Excel excel)
        {
            _logger = logger;
            _excel = excel;
        }

        public void OnGet()
        {

        }

        public void OnPostAdd()
        {
            TempData["Action"] = "Add";
        }

        public void OnPostAddConfirm()
        {
            TempData["AlertMessage"] = "新增成功";
        }
        public void OnPostQuery() {
			TempData["AlertMessage"] = "查詢成功";
		}

        public void OnPostImport()
        {
            _logger.LogInformation("Importing...");
            
            if (ImportedFile == null)
            {
                TempData["AlertMessage"] = "請選擇檔案";
                return;
            }

            using (var memoryStream = new MemoryStream())
            {
                ImportedFile.CopyTo(memoryStream);
                var fileBytes = memoryStream.ToArray();
                var ds = _excel.ImportFromExcel(fileBytes);
            }
        }
    }
}

Pages/Module/Form/Leave.cshtml.cs
using DocumentFormat.OpenXml.Bibliography;
using DocumentFormat.OpenXml.Wordprocessing;
using HR_WorkFlow.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.SqlClient;


namespace HR_WorkFlow.Pages.Module.Form
{
    [Authorize]
    public class LeaveModel : PageModel
    {
        [BindProperty]
        public String? Leave_No { get; set; }

        [BindProperty]
        public String? Leave { get; set; }
        [BindProperty]
        public DateTime? Start_Date { get; set; }

        [BindProperty]
        public DateTime? End_Date { get; set; }

        [BindProperty]
        public String? Leave_Content { get; set; }

        [BindProperty]
        public String? Sign_No { get; set; }

        [BindProperty]
        public Decimal? Hours { get; set; }

        [BindProperty]
        public String? Status { get; set; }

        [BindProperty]
        public List<string> SelectedIds { get; set; }

        [BindProperty]
        public List<int> SelectedItems { get; set; }
        protected SqlDatabase Database { get; set; }    //引用共用函式(SQLService)
        protected Common Common { get; set; }    

        public LeaveModel(SqlDatabase database, Common common)   //注入服務(SQL&log)
        {
            Database = database;
            Common = common;
        }
        public IActionResult OnGet()
        {
            return Page();
        }


        public class LeaveData
        {
            public int? Leave_No { get; set; }
            public String? Leave { get; set; }
            public DateTime? Start_Date { get; set; }
            public DateTime? End_Date { get; set; }
            public String? Leave_Content { get; set; }
            public String? Status { get; set; }
            public String? Sign_No { get; set; }

        }

        private DataTable QueryLeaveData()
        {

            string strSQL = @"
SELECT Leave_Overtime.*, 
               D_Leave.Code_Name AS LeaveName,
               D_Status.Code_Name AS StatusName,
               EMP_Data.EMP_Name AS SignNo
  FROM Leave_Overtime WITH(NOLOCK)
 INNER JOIN DDL_Setting  AS D_Leave WITH(NOLOCK) ON Leave_Overtime.Leave = D_Leave.Code_No AND D_Leave.DDL_No = 'L01'
 INNER JOIN DDL_Setting AS D_Status WITH(NOLOCK) ON Leave_Overtime.Status = D_Status.Code_No AND D_Status.DDL_No = 'F01' AND D_Status.Code_No = '0'
     LEFT JOIN EMP_Data AS EMP_Data WITH(NOLOCK) ON Leave_Overtime.Sign_No = EMP_Data.EMP_No
WHERE Leave_Overtime.Emp_No=@userName
ORDER BY Leave_No DESC
";
            var userName = User.Identity?.Name;
            SqlCommand command = Database.CreateCommand(strSQL);
            command.Parameters.AddWithValue("@userName", userName);
            DataTable dt = new DataTable();
            SqlDataAdapter da = new SqlDataAdapter(command);
            da.Fill(dt);
            return dt;
        }
        public IActionResult OnPostAdd()
        {
            if (Start_Date == null || End_Date == null || string.IsNullOrWhiteSpace(Leave) || string.IsNullOrWhiteSpace(Sign_No) || string.IsNullOrWhiteSpace(Leave_Content))
            {
                TempData["AlertMessage"] = "請填寫所有必填欄位";
                return Page();
            }

            // 檢查日期合法性
            if (End_Date < Start_Date)
            {
                TempData["AlertMessage"] = "結束日期不能大於起始日期";
                return Page();
            }
            DataTable hoursTable = Common.GetLeavehours(Start_Date.ToString(), End_Date.ToString());
            if (hoursTable.Rows.Count > 0)
            {
                int days = hoursTable.Rows[0].Field<int>("Days");
                decimal hours = hoursTable.Rows[0].Field<decimal>("Hours");
                const int HoursPerDay = 8;
                // 將天數換成小時數
                decimal totalHours = days * HoursPerDay + hours;

                DataTable leaveNoTable = Common.GetLeaveNo();
                string leaveNo = leaveNoTable.Rows[0][0].ToString();

                string insertLeaveQuery = @"
                INSERT INTO LEAVE_OVERTIME 
                                         (Leave_No,
                                          Emp_No,
                                          Sign_No,
                                          Start_Date,
                                          End_Date,
                                          Leave_Content,
                                          Status,Leave,
                                          Hours,
                                          Creater,
                                          Create_Date)
                         VALUES (@Leave_No,
                                          @Emp_No,
                                          @Sign_No,
                                          @Start_Date,
                                          @End_Date,
                                          @Leave_Content,
                                          @Status,
                                          @Leave,
                                          @Hours,
                                          @Emp_No,
                                          GetDate())
";

            var Emp_No = User.Identity?.Name;

            SqlCommand command = Database.CreateCommand(insertLeaveQuery);
            command.Parameters.AddWithValue("@Leave_No", leaveNo);
            command.Parameters.AddWithValue("@Emp_No", Emp_No);
            command.Parameters.AddWithValue("@Sign_No", this.Sign_No);
            command.Parameters.AddWithValue("@Start_Date", (Object)Start_Date! ?? DBNull.Value);
            command.Parameters.AddWithValue("@End_Date", (Object)End_Date! ?? DBNull.Value);
            command.Parameters.AddWithValue("@Status", '0');
            command.Parameters.AddWithValue("@Leave", this.Leave);
            command.Parameters.AddWithValue("@Leave_Content", Leave_Content);
            command.Parameters.AddWithValue("@Hours", totalHours);
            command.ExecuteNonQuery();

            //call Query
            //dt  存到LIST 顯示View.bag
            ViewData["QueryLeaveData"] = this.QueryLeaveData();
            TempData["AlertMessage"] = "新增成功";
            return RedirectToPage();
            }
            else
            {
                TempData["AlertMessage"] = "計算時數失敗";
                return Page();
            }
        }
        public override void OnPageHandlerExecuting(PageHandlerExecutingContext context)   //每次都會執行
        {
            base.OnPageHandlerExecuting(context);
            ViewData["QueryLeaveData"] = this.QueryLeaveData();

        }
        public IActionResult OnPostSearch()
        {
            try
            {
              
                string searchQuery = @"
SELECT Leave_Overtime.*, 
               D_Leave.Code_Name AS LeaveName,
               D_Status.Code_Name AS StatusName,
               EMP_Data.EMP_Name AS SignNo
  FROM Leave_Overtime WITH(NOLOCK)
 INNER JOIN DDL_Setting  AS D_Leave WITH(NOLOCK) ON Leave_Overtime.Leave = D_Leave.Code_No AND D_Leave.DDL_No = 'L01'
 INNER JOIN DDL_Setting AS D_Status WITH(NOLOCK) ON Leave_Overtime.Status = D_Status.Code_No AND D_Status.DDL_No = 'F01' AND D_Status.Code_No = '0'
     LEFT JOIN EMP_Data AS EMP_Data WITH(NOLOCK) ON Leave_Overtime.Sign_No = EMP_Data.EMP_No
WHERE 1 = 1
    AND D_Status.Code_No = '0'
    AND (Leave_No = @Leave_No OR ISNULL(@Leave_No,'') ='')
    AND (Leave = @Leave OR ISNULL(@Leave,'') ='')
    AND (Sign_No = @Sign_No OR ISNULL(@Sign_No,'') ='')
    AND (CONVERT(DATE, Start_Date) >= @Start_Date OR ISNULL(@Start_Date, '') = '')
    AND (CONVERT(DATE, End_Date) <= @End_Date OR ISNULL(@End_Date, '') = '')
    AND (LEAVE_CONTENT LIKE '%' + @Leave_Content + '%' OR ISNULL(@Leave_Content, '') = '')
ORDER BY Leave_No DESC
                 ";
                SqlCommand command = Database.CreateCommand(searchQuery);
                command.Parameters.AddWithValue("@Leave_No", (Object)Leave_No! ?? DBNull.Value);
                command.Parameters.AddWithValue("@Leave", (Object)Leave! ?? DBNull.Value);
                command.Parameters.AddWithValue("@Sign_No", (Object)Sign_No! ?? DBNull.Value);
                command.Parameters.AddWithValue("@Start_Date", Start_Date.HasValue ? (object)Start_Date.Value.Date : DBNull.Value);
                command.Parameters.AddWithValue("@End_Date", End_Date.HasValue ? (object)End_Date.Value.Date : DBNull.Value);
                command.Parameters.AddWithValue("@Leave_Content", (Object)Leave_Content! ?? DBNull.Value);
                DataTable dt = new DataTable();
                SqlDataAdapter da = new SqlDataAdapter(command);
                da.Fill(dt);
                ViewData["QueryLeaveData"] = dt;
            }
            catch
            {
                TempData["AlertMessage"] = "查詢時發生錯誤";
            }
            return Page();


        }

        public LeaveData GetLeaveDataByLeaveNo(int leaveNo)
        {

            string strSQL = @"
                    SELECT Leave_No, Leave, Start_Date, End_Date, Leave_Content, Status, Sign_No
                     FROM Leave_Overtime WITH(NOLOCK)
                   WHERE Leave_No = @Leave_No
    ";

            SqlCommand command = Database.CreateCommand(strSQL);
            command.Parameters.AddWithValue("@Leave_No", leaveNo);

            using (SqlDataReader reader = command.ExecuteReader())
            {
                if (reader.Read())
                {
                    return new LeaveData
                    {
                        Leave_No = reader.GetInt32(reader.GetOrdinal("Leave_No")),

Pages/Module/Query/QueryClassSchedule.cshtml.cs
using DocumentFormat.OpenXml.Bibliography;
using DocumentFormat.OpenXml.Drawing.Charts;
using DocumentFormat.OpenXml.Wordprocessing;
using HR_WorkFlow.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Threading.Tasks;
using Newtonsoft.Json;
using static HR_WorkFlow.Pages.Module.Form.LeaveModel;
using DataTable = System.Data.DataTable;

namespace HR_WorkFlow.Pages.Module.Query
{
    [Authorize]
    public class QueryClassScheduleModel : PageModel
    {

        protected SqlDatabase Database { get; set; }

        //List<CalendarData> eventsList = new List<CalendarData>();

        public QueryClassScheduleModel(SqlDatabase database)
        {
            Database = database;

        }
        public class CalendarDataRequest
        {
            public string Emp_No { get; set; }
            public DateTime HR_Day { get; set; }
            public string DayNight { get; set; }
            public string Type { get; set; }
            public string Shift { get; set; } // 添加 '班表' 屬性
        }

        public JsonResult OnPostCalendarData([FromBody] CalendarDataRequest requestModel)
        {

            try
            {
                string strSQL = @"
            SELECT HR_DAY,
                CASE
                    WHEN TYPE = 0 AND DAYNIGHT = 0 THEN '早班'
                    WHEN TYPE = 0 AND DAYNIGHT = 1 THEN '晚班'
                    WHEN TYPE = 0 AND DAYNIGHT = 2 THEN '中班'
                    WHEN DAYNIGHT = 3 AND TYPE = 1 THEN '休息日'
                    WHEN DAYNIGHT = 3 AND TYPE = 2 THEN '例假'
                    WHEN DAYNIGHT = 3 AND TYPE = 3 THEN '國定假日'
                    ELSE '異常'
                END AS Shift
            FROM
                HelpDesk WITH(NOLOCK)
            WHERE EMP_No = @EmpNo;
        ";
                var userName = User.Identity?.Name;

                SqlCommand command = Database.CreateCommand(strSQL);
                command.Parameters.AddWithValue("@EmpNo", userName);
                DataTable dt = new DataTable();
                SqlDataAdapter da = new SqlDataAdapter(command);
                da.Fill(dt);

                
                string jsonResult = ConvertDataTableToJson(dt);
                return new JsonResult(jsonResult);
            }
            catch (Exception ex)
            {
                // Log or handle the exception
                return new JsonResult($"Error: {ex.Message}");
            }
        }
        private string ConvertDataTableToJson(DataTable dataTable)
        {
            var rows = new List<Dictionary<string, object>>();
            foreach (DataRow row in dataTable.Rows)
            {
                var dict = new Dictionary<string, object>();
                foreach (DataColumn col in dataTable.Columns)
                {
                    if (col.ColumnName == "HR_DAY" && row[col] is DateTime)
                    {
                        // 將日期轉換為字串格式，只保留日期部分
                        dict[col.ColumnName] = ((DateTime)row[col]).ToString("yyyy-MM-dd");
                    }
                    else
                    {
                        dict[col.ColumnName] = row[col];
                    }
                }
                rows.Add(dict);
            }

            return JsonConvert.SerializeObject(rows);
        }


    }
}

Pages/Module/Query/Attendance.cshtml
@page
@using HR_WorkFlow.Services
@using System.Security.Claims
@using static HR_WorkFlow.Pages.Module.Query.AttendanceModel
@using System.Data
@model HR_WorkFlow.Pages.Module.Query.AttendanceModel
@inject MenuBase MenuBase
@inject Common Common

@{
    ViewData["Title"] = "Attendance";
    ViewBag.ShowHeader = true;
    ViewBag.Menu = MenuBase.GetMenu();
    ViewData["ABS_StatusOptions"] = Common.GetDropdownOptions("Q01", "");
    var userRole = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;
}
<style>
    #pagination {
        text-align: center;
        margin-top: 10px; /* 調整上邊距 */
    }

        #pagination a {
            margin: 0 5px; /* 調整每個按鈕的間距 */
            display: inline-block;
            text-decoration: none;
            padding: 5px 10px;
            border: 1px solid #ddd;
            cursor: pointer;
        }
</style>



<body>
    <form action="" method="post">
        <div class="row">
            <div class="col-md-4">
                <div class="row">
                    <label asp-for="Start_Time" class="col-md-4 col-form-label text-end">時間(起):</label>
                    <div class="col-md-8">
                        <input type="Date" class="form-control" asp-for="Start_Time" />
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="row">
                    <label asp-for="End_Time" class="col-md-4 col-form-label text-end">時間(迄):</label>
                    <div class="col-md-8">
                        <input type="Date" class="form-control" asp-for="End_Time">
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="row">
                    <label for="Status" class="col-md-4 col-form-label text-end">狀態:</label>
                    <div class="col-md-6">
                        <select class="form-select" asp-for="Status" aria-label="Default select example">
                            @if (ViewData["ABS_StatusOptions"] != null)
                            {
                                @foreach (DataRow item in ((DataTable)ViewData["ABS_StatusOptions"]!).Rows)
                                {
                                    <option value="@item["Code_No"]">@item["Code_Name"]</option>
                                }
                            }
                        </select>
                    </div>
                </div>
            </div>

            @if (userRole == "9")
            {
                <div class="row">
                    <div class="col-md-4 my-3 ">
                        <div class="row">
                            <label for="Status" class="col-md-4 col-form-label text-end">員工姓名:</label>
                            <div class="col-md-8">
                                <select class="form-select" asp-for="Status" aria-label="Default select example">
                                    @* 我這裡沒做事 申請平台協助我組成多選選單 *@
                                    <option value=""></option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>

        <div class="col-12 d-md-flex justify-content-md-between">
            <div class="d-grid gap-2 d-md-flex">
                <button asp-page-handler="Query" class="btn btn-outline-secondary">查詢</button>
                <button asp-page-handler="Export" class="btn btn-outline-success">匯出</button>
            </div>
        </div>
        <hr style="margin:20px;" />

        <table class="row Attendance_result1 data-table" id="data-table">
            <thead>
                <tr class="d-flex align-items-center py-2" style="background-color:gainsboro;border-radius:3px">

                    <th class="col-2 text-center">日期</th>
                    <th class="col-2 text-center">上班時間</th>
                    <th class="col-2 text-center">下班時間</th>
                    <th class="col-2 text-center">出勤時數</th>
                    <th class="col-2 text-center">狀態</th>
                    <th class="col-2 text-center">出勤狀況</th>
                </tr>
            </thead>
            @if (Model.Absence_Table?.Rows.Count > 0)
            {
                <tbody class="Attendance_table row">
                    @if (ViewData["QueryResult"] is DataTable dataTable)
                    {
                        foreach (DataRow row in Model.Absence_Table.Rows)
                        {
                            <tr class="data-row d-flex align-items-center py-2 ms-2" style="border-bottom:1px solid lightgrey">
                                <td class="col-2 text-center">@DateTime.Parse(row["Date"].ToString()).ToString("yyyy-MM-dd")</td>
                                <td class="col-2 text-center">@DateTime.Parse(row["Punch_In_Time"].ToString()).ToString("HH:mm:ss")</td>
                                <td class="col-2 text-center">@DateTime.Parse(row["Punch_Out_Time"].ToString()).ToString("HH:mm:ss")</td>
                                <td class="col-2 text-center">@row["Working_Hours"]</td>
                                <td class="col-2 text-center">@row["Attendance_Status"]</td>
                                <td class="col-2 text-center">@row["Attendance_Condition"]</td>
                            </tr>
                        }
                    }
                </tbody>
            }
        </table>
       <div id="pagination"></div>

    </form>
        
        <div class="SignStatus_title1 container">
            <div style="text-align: center;">
                <script>
                    const pageSize = 10;
                    const table = document.getElementById('data-table');
                    const pagination = document.getElementById('pagination');
                    let currentPage = 1;


                    function displayPage(page) {
                        const rows = table.getElementsByClassName('data-row');
                        // const rows = table.getElementsByClassName('data-row d-flex align-items-center');
                        // data - row d - flex align - items - center
                        const totalRows = rows.length;
                        const totalPages = Math.ceil(totalRows / pageSize);
                        currentPage = page;

                        // 显示或隐藏行
                        for (let i = 0; i < totalRows; i++) {
                            rows[i].style.display = (i >= pageSize * (page - 1) && i < pageSize * page) ? '' : 'none';
                        }

                        // 清除舊的分頁連結
                        pagination.innerHTML = '';

                        // 添加“往前一頁”連結
                        const prevLink = document.createElement('a');
                        prevLink.href = '#';
                        prevLink.textContent = '<';
                        prevLink.addEventListener('click', (event) => {
                            event.preventDefault();
                            if (page > 1) {
                                displayPage(page - 1);
                            }
                        });
                        pagination.appendChild(prevLink);

                        // 添加數字連結
                        for (let i = 1; i <= totalPages; i++) {
                            const link = document.createElement('a');
                            link.href = '#';
                            link.textContent = i;
                            link.addEventListener('click', (event) => {
                                event.preventDefault();
                                displayPage(i);
                            });
                            pagination.appendChild(link);
                        }

                        // 添加“往後一頁”連結
                        const nextLink = document.createElement('a');
                        nextLink.href = '#';
                        nextLink.textContent = '>';
                        nextLink.addEventListener('click', (event) => {
                            event.preventDefault();
                            if (page < totalPages) {
                                displayPage(page + 1);
                            }
                        });
                        pagination.appendChild(nextLink);
                    }
                    displayPage(1); // 初始化显示第一页
                </script>
            </div>
        </div>
    
</body>



Pages/Module/Query/QueryClassSchedule.cshtml
@page
@using HR_WorkFlow.Services;
@using System.Security.Claims;
@using System.Data;
@using Microsoft.AspNetCore.Antiforgery
@inject MenuBase MenuBase
@inject Common Common
@inject IAntiforgery antiforgery
@model HR_WorkFlow.Pages.Module.Query.QueryClassScheduleModel

@{
    ViewData["Title"] = "QueryClassSchedule";
    ViewBag.ShowHeader = true;
    ViewBag.Menu = MenuBase.GetMenu();
    var antiForgery = antiforgery.GetAndStoreTokens(HttpContext).RequestToken;
    // ViewData["Status"] = Common.GetDropdownOptions("P01", "");
}
<style>

    #calendar {
        width: 80%;
        margin: auto;
    }

    .fc .fc-col-header-cell-cushion, .fc .fc-daygrid-day-number {
    color:black;
    text-decoration:none;
    }

    .fc-direction-ltr .fc-daygrid-week-number{
        text-decoration: none;
    }
</style>

<body>
    <div id='calendar'></div>
    <script src="~/lib/fullcalendar/dist/index.global.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@3.10.2/dist/locale/zh-tw.js"></script>
    <script>
        var event = [];
        document.addEventListener('DOMContentLoaded', async function () {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                dayMaxEvents: false,
                headerToolbar: {
                    left: 'prev,next',
                    center: 'title',
                    right: 'today'
                },
                locale: 'zh-tw',
                firstDay: 1,
                weekNumbers: true,
                weekNumberFormat: {
                    week: 'numeric'
                },
                buttonText: {
                    today: '今天'
                },
                dayHeaderFormat: {
                    weekday: 'short'
                },
                dayHeaderContent: function (args) {
                    // 將星期的英文全名轉換為中文
                    var weekdays = ["日", "一", "二", "三", "四", "五", "六"];
                    return '星期' + weekdays[args.date.getDay()];
                },
                fixedWeekCount: false,
                events: []
            });
            CalendarData(calendar);
            calendar.render();
        });
        async function CalendarData(calendar) {
            var response = await fetch('@Url.Page("", "CalendarData")', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'RequestVerificationToken': '@antiForgery'
                },
                body: JSON.stringify(),
            });
            const res = await response.json();
            
            // 將 res 轉換為陣列
            const dataArray = Array.isArray(res) ? res : JSON.parse(res);

            function getEventColor(shift) {
                switch (shift) {
                    case '早班':
                        return 'tblue';
                    case '晚班':
                        return 'green';
                    case '中班':
                        return 'orange';
                    case '休息日':
                        return 'gray';
                    case '例假':
                        return 'purple';
                    case '國定假日':
                        return 'lightpurple';
                    default:
                        return 'red';
                }
            }

            dataArray.forEach(value => {
                const eventColor = getEventColor(value['Shift']);
                event.push({
                    title: value['Shift'],
                    start: value['HR_DAY'],
                    end: value['HR_DAY'],
                    color: eventColor
                });
            });

            calendar.addEventSource(event);
        }

    </script>
   
</body>
