Pages/Module/Announcement/Index.cshtml.cs
using HR_WorkFlow.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HR_WorkFlow.Pages.Module.Announcement
{
    [Authorize]
    public class IndexModel : PageModel
    {
        [BindProperty]
        public string? Username { get; set; }   //前端欄位綁定

        [BindProperty]
        public string? Password { get; set; }

        [BindProperty]
        public IFormFile? ImportedFile { get; set; }

        private readonly ILogger<IndexModel> _logger;
        private readonly Excel _excel;

        public IndexModel(ILogger<IndexModel> logger, Excel excel)
        {
            _logger = logger;
            _excel = excel;
        }

        public void OnGet()
        {

        }

        public void OnPostAdd()
        {
            TempData["Action"] = "Add";
        }

        public void OnPostAddConfirm()
        {
            TempData["AlertMessage"] = "新增成功";
        }
        public void OnPostQuery() {
			TempData["AlertMessage"] = "查詢成功";
		}

        public void OnPostImport()
        {
            _logger.LogInformation("Importing...");
            
            if (ImportedFile == null)
            {
                TempData["AlertMessage"] = "請選擇檔案";
                return;
            }

            using (var memoryStream = new MemoryStream())
            {
                ImportedFile.CopyTo(memoryStream);
                var fileBytes = memoryStream.ToArray();
                var ds = _excel.ImportFromExcel(fileBytes);
            }
        }
    }
}

Pages/Module/Form/Leave.cshtml.cs
using DocumentFormat.OpenXml.Bibliography;
using DocumentFormat.OpenXml.Wordprocessing;
using HR_WorkFlow.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.SqlClient;


namespace HR_WorkFlow.Pages.Module.Form
{
    [Authorize]
    public class LeaveModel : PageModel
    {
        [BindProperty]
        public String? Leave_No { get; set; }

        [BindProperty]
        public String? Leave { get; set; }
        [BindProperty]
        public DateTime? Start_Date { get; set; }

        [BindProperty]
        public DateTime? End_Date { get; set; }

        [BindProperty]
        public String? Leave_Content { get; set; }

        [BindProperty]
        public String? Sign_No { get; set; }

        [BindProperty]
        public Decimal? Hours { get; set; }

        [BindProperty]
        public String? Status { get; set; }

        [BindProperty]
        public List<string> SelectedIds { get; set; }

        [BindProperty]
        public List<int> SelectedItems { get; set; }
        protected SqlDatabase Database { get; set; }    //引用共用函式(SQLService)
        protected Common Common { get; set; }    

        public LeaveModel(SqlDatabase database, Common common)   //注入服務(SQL&log)
        {
            Database = database;
            Common = common;
        }
        public IActionResult OnGet()
        {
            return Page();
        }


        public class LeaveData
        {
            public int? Leave_No { get; set; }
            public String? Leave { get; set; }
            public DateTime? Start_Date { get; set; }
            public DateTime? End_Date { get; set; }
            public String? Leave_Content { get; set; }
            public String? Status { get; set; }
            public String? Sign_No { get; set; }

        }

        private DataTable QueryLeaveData()
        {

            string strSQL = @"
SELECT Leave_Overtime.*, 
               D_Leave.Code_Name AS LeaveName,
               D_Status.Code_Name AS StatusName,
               EMP_Data.EMP_Name AS SignNo
  FROM Leave_Overtime WITH(NOLOCK)
 INNER JOIN DDL_Setting  AS D_Leave WITH(NOLOCK) ON Leave_Overtime.Leave = D_Leave.Code_No AND D_Leave.DDL_No = 'L01'
 INNER JOIN DDL_Setting AS D_Status WITH(NOLOCK) ON Leave_Overtime.Status = D_Status.Code_No AND D_Status.DDL_No = 'F01' AND D_Status.Code_No = '0'
     LEFT JOIN EMP_Data AS EMP_Data WITH(NOLOCK) ON Leave_Overtime.Sign_No = EMP_Data.EMP_No
WHERE Leave_Overtime.Emp_No=@userName
ORDER BY Leave_No DESC
";
            var userName = User.Identity?.Name;
            SqlCommand command = Database.CreateCommand(strSQL);
            command.Parameters.AddWithValue("@userName", userName);
            DataTable dt = new DataTable();
            SqlDataAdapter da = new SqlDataAdapter(command);
            da.Fill(dt);
            return dt;
        }
        public IActionResult OnPostAdd()
        {
            if (Start_Date == null || End_Date == null || string.IsNullOrWhiteSpace(Leave) || string.IsNullOrWhiteSpace(Sign_No) || string.IsNullOrWhiteSpace(Leave_Content))
            {
                TempData["AlertMessage"] = "請填寫所有必填欄位";
                return Page();
            }

            // 檢查日期合法性
            if (End_Date < Start_Date)
            {
                TempData["AlertMessage"] = "結束日期不能大於起始日期";
                return Page();
            }
            DataTable hoursTable = Common.GetLeavehours(Start_Date.ToString(), End_Date.ToString());
            if (hoursTable.Rows.Count > 0)
            {
                int days = hoursTable.Rows[0].Field<int>("Days");
                decimal hours = hoursTable.Rows[0].Field<decimal>("Hours");
                const int HoursPerDay = 8;
                // 將天數換成小時數
                decimal totalHours = days * HoursPerDay + hours;

                DataTable leaveNoTable = Common.GetLeaveNo();
                string leaveNo = leaveNoTable.Rows[0][0].ToString();

                string insertLeaveQuery = @"
                INSERT INTO LEAVE_OVERTIME 
                                         (Leave_No,
                                          Emp_No,
                                          Sign_No,
                                          Start_Date,
                                          End_Date,
                                          Leave_Content,
                                          Status,Leave,
                                          Hours,
                                          Creater,
                                          Create_Date)
                         VALUES (@Leave_No,
                                          @Emp_No,
                                          @Sign_No,
                                          @Start_Date,
                                          @End_Date,
                                          @Leave_Content,
                                          @Status,
                                          @Leave,
                                          @Hours,
                                          @Emp_No,
                                          GetDate())
";

            var Emp_No = User.Identity?.Name;

            SqlCommand command = Database.CreateCommand(insertLeaveQuery);
            command.Parameters.AddWithValue("@Leave_No", leaveNo);
            command.Parameters.AddWithValue("@Emp_No", Emp_No);
            command.Parameters.AddWithValue("@Sign_No", this.Sign_No);
            command.Parameters.AddWithValue("@Start_Date", (Object)Start_Date! ?? DBNull.Value);
            command.Parameters.AddWithValue("@End_Date", (Object)End_Date! ?? DBNull.Value);
            command.Parameters.AddWithValue("@Status", '0');
            command.Parameters.AddWithValue("@Leave", this.Leave);
            command.Parameters.AddWithValue("@Leave_Content", Leave_Content);
            command.Parameters.AddWithValue("@Hours", totalHours);
            command.ExecuteNonQuery();

            //call Query
            //dt  存到LIST 顯示View.bag
            ViewData["QueryLeaveData"] = this.QueryLeaveData();
            TempData["AlertMessage"] = "新增成功";
            return RedirectToPage();
            }
            else
            {
                TempData["AlertMessage"] = "計算時數失敗";
                return Page();
            }
        }
        public override void OnPageHandlerExecuting(PageHandlerExecutingContext context)   //每次都會執行
        {
            base.OnPageHandlerExecuting(context);
            ViewData["QueryLeaveData"] = this.QueryLeaveData();

        }
        public IActionResult OnPostSearch()
        {
            try
            {
              
                string searchQuery = @"
SELECT Leave_Overtime.*, 
               D_Leave.Code_Name AS LeaveName,
               D_Status.Code_Name AS StatusName,
               EMP_Data.EMP_Name AS SignNo
  FROM Leave_Overtime WITH(NOLOCK)
 INNER JOIN DDL_Setting  AS D_Leave WITH(NOLOCK) ON Leave_Overtime.Leave = D_Leave.Code_No AND D_Leave.DDL_No = 'L01'
 INNER JOIN DDL_Setting AS D_Status WITH(NOLOCK) ON Leave_Overtime.Status = D_Status.Code_No AND D_Status.DDL_No = 'F01' AND D_Status.Code_No = '0'
     LEFT JOIN EMP_Data AS EMP_Data WITH(NOLOCK) ON Leave_Overtime.Sign_No = EMP_Data.EMP_No
WHERE 1 = 1
    AND D_Status.Code_No = '0'
    AND (Leave_No = @Leave_No OR ISNULL(@Leave_No,'') ='')
    AND (Leave = @Leave OR ISNULL(@Leave,'') ='')
    AND (Sign_No = @Sign_No OR ISNULL(@Sign_No,'') ='')
    AND (CONVERT(DATE, Start_Date) >= @Start_Date OR ISNULL(@Start_Date, '') = '')
    AND (CONVERT(DATE, End_Date) <= @End_Date OR ISNULL(@End_Date, '') = '')
    AND (LEAVE_CONTENT LIKE '%' + @Leave_Content + '%' OR ISNULL(@Leave_Content, '') = '')
ORDER BY Leave_No DESC
                 ";
                SqlCommand command = Database.CreateCommand(searchQuery);
                command.Parameters.AddWithValue("@Leave_No", (Object)Leave_No! ?? DBNull.Value);
                command.Parameters.AddWithValue("@Leave", (Object)Leave! ?? DBNull.Value);
                command.Parameters.AddWithValue("@Sign_No", (Object)Sign_No! ?? DBNull.Value);
                command.Parameters.AddWithValue("@Start_Date", Start_Date.HasValue ? (object)Start_Date.Value.Date : DBNull.Value);
                command.Parameters.AddWithValue("@End_Date", End_Date.HasValue ? (object)End_Date.Value.Date : DBNull.Value);
                command.Parameters.AddWithValue("@Leave_Content", (Object)Leave_Content! ?? DBNull.Value);
                DataTable dt = new DataTable();
                SqlDataAdapter da = new SqlDataAdapter(command);
                da.Fill(dt);
                ViewData["QueryLeaveData"] = dt;
            }
            catch
            {
                TempData["AlertMessage"] = "查詢時發生錯誤";
            }
            return Page();


        }

        public LeaveData GetLeaveDataByLeaveNo(int leaveNo)
        {

            string strSQL = @"
                    SELECT Leave_No, Leave, Start_Date, End_Date, Leave_Content, Status, Sign_No
                     FROM Leave_Overtime WITH(NOLOCK)
                   WHERE Leave_No = @Leave_No
    ";

            SqlCommand command = Database.CreateCommand(strSQL);
            command.Parameters.AddWithValue("@Leave_No", leaveNo);

            using (SqlDataReader reader = command.ExecuteReader())
            {
                if (reader.Read())
                {
                    return new LeaveData
                    {
                        Leave_No = reader.GetInt32(reader.GetOrdinal("Leave_No")),

Pages/Module/Query/QueryClassSchedule.cshtml.cs
using DocumentFormat.OpenXml.Bibliography;
using DocumentFormat.OpenXml.Drawing.Charts;
using DocumentFormat.OpenXml.Wordprocessing;
using HR_WorkFlow.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Threading.Tasks;
using Newtonsoft.Json;
using static HR_WorkFlow.Pages.Module.Form.LeaveModel;
using DataTable = System.Data.DataTable;

namespace HR_WorkFlow.Pages.Module.Query
{
    [Authorize]
    public class QueryClassScheduleModel : PageModel
    {

        protected SqlDatabase Database { get; set; }

        //List<CalendarData> eventsList = new List<CalendarData>();

        public QueryClassScheduleModel(SqlDatabase database)
        {
            Database = database;

        }
        public class CalendarDataRequest
        {
            public string Emp_No { get; set; }
            public DateTime HR_Day { get; set; }
            public string DayNight { get; set; }
            public string Type { get; set; }
            public string Shift { get; set; } // 添加 '班表' 屬性
        }

        public JsonResult OnPostCalendarData([FromBody] CalendarDataRequest requestModel)
        {

            try
            {
                string strSQL = @"
            SELECT HR_DAY,
                CASE
                    WHEN TYPE = 0 AND DAYNIGHT = 0 THEN '早班'
                    WHEN TYPE = 0 AND DAYNIGHT = 1 THEN '晚班'
                    WHEN TYPE = 0 AND DAYNIGHT = 2 THEN '中班'
                    WHEN DAYNIGHT = 3 AND TYPE = 1 THEN '休息日'
                    WHEN DAYNIGHT = 3 AND TYPE = 2 THEN '例假'
                    WHEN DAYNIGHT = 3 AND TYPE = 3 THEN '國定假日'
                    ELSE '異常'
                END AS Shift
            FROM
                HelpDesk WITH(NOLOCK)
            WHERE EMP_No = @EmpNo;
        ";
                var userName = User.Identity?.Name;

                SqlCommand command = Database.CreateCommand(strSQL);
                command.Parameters.AddWithValue("@EmpNo", userName);
                DataTable dt = new DataTable();
                SqlDataAdapter da = new SqlDataAdapter(command);
                da.Fill(dt);

                
                string jsonResult = ConvertDataTableToJson(dt);
                return new JsonResult(jsonResult);
            }
            catch (Exception ex)
            {
                // Log or handle the exception
                return new JsonResult($"Error: {ex.Message}");
            }
        }
        private string ConvertDataTableToJson(DataTable dataTable)
        {
            var rows = new List<Dictionary<string, object>>();
            foreach (DataRow row in dataTable.Rows)
            {
                var dict = new Dictionary<string, object>();
                foreach (DataColumn col in dataTable.Columns)
                {
                    if (col.ColumnName == "HR_DAY" && row[col] is DateTime)
                    {
                        // 將日期轉換為字串格式，只保留日期部分
                        dict[col.ColumnName] = ((DateTime)row[col]).ToString("yyyy-MM-dd");
                    }
                    else
                    {
                        dict[col.ColumnName] = row[col];
                    }
                }
                rows.Add(dict);
            }

            return JsonConvert.SerializeObject(rows);
        }


    }
}

Pages/Module/Form/Leave.cshtml
@page
@using HR_WorkFlow.Services;
@using System.Security.Claims;
@using System.Data;
@using Microsoft.AspNetCore.Antiforgery
@model HR_WorkFlow.Pages.Module.Form.LeaveModel
@inject MenuBase MenuBase
@inject Common Common
@inject IAntiforgery antiforgery

@{
    ViewData["Title"] = "Leave";
    ViewBag.ShowHeader = true;
    ViewBag.Menu = MenuBase.GetMenu();
    ViewData["LeaveOptions"] = Common.GetDropdownOptions("L01","");
    var userName = User.Identity?.Name;
    ViewData["Signer"] = Common.GetSigner(userName);
    var antiForgery = antiforgery.GetAndStoreTokens(HttpContext).RequestToken;
}

<body>
    <form method="post" novalidate>

        <div class="row">
            @* 特休天數 *@
            <div class="col-12">特休剩    天      給薪病假剩    天      生理假    天</div>
            
            <div class="col-md-6 leave-item">
                @* col-1:單號 *@
                <div class="row my-4">
                    <label for="leave_no" class="col-md-3 col-form-label text-end">單號</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" id="Leave_No" asp-for="Leave_No" name="Leave_No" maxlength="9" placeholder="僅供查詢使用,例:202312001">
                    </div>
                </div>
                @* col-1:時間(起) *@
                <div class="row my-4">
                    <label for="Start_Date" class="col-md-3 col-form-label text-end form-label"><span style="color:red">*</span> 時間(起)</label>
                    <div class='col-md-9'>
                        <input type='datetime-local' asp-for="Start_Date" class="form-control" id="Start_Date" required name="Start_Date" />
                    </div>
                </div>
                @* col-1:假別 *@
                <div class="row my-4">
                    <label for="Leave" class="col-md-3 col-form-label text-end form-label"><span style="color:red">*</span> 假別</label>
                    <div class="col-md-9">
                        <select class="form-select" asp-for="Leave" aria-label="Default select example" id="Leave" required name="Leave">
                            @* <option value="" selected></option> *@
                            @if (ViewData["LeaveOptions"] != null)
                            {
                                @foreach (DataRow item in ((DataTable)ViewData["LeaveOptions"]!).Rows)
                                {
                                    <option value="@item["Code_No"]">@item["Code_Name"]</option>
                                }
                            }
                        </select>
                    </div>
                </div>
            </div>
            @* col-2:時間(迄) *@
            <div class="col-md-6 leave-item align-self-end">
                <div class="row my-4">
                    @*時數統計 *@
                    <p class="text-end" id="Hours"></p>
                    <label for="End_Date" class="col-md-3 col-form-label text-end form-label"><span style="color:red">*</span> 時間(迄)</label>
                    <div class="col-md-9">
                        <input type="datetime-local" asp-for="End_Date" class="form-control" id="End_Date" required name="End_Date" />
                    </div>
                </div>
                @* col-2:簽核人 *@
                <div class="row my-4">
                    <label for="Sign_No" class="col-md-3 col-form-label text-end form-label"><span style="color:red">*</span> 簽核人</label>
                    <div class="col-md-9">
                        <select class="form-select" asp-for="Sign_No" aria-label="Default select example" id="Sign_No" required name="Sign_No">
                            @if (ViewData["Signer"] != null)
                            {
                                @foreach (DataRow item in ((DataTable)ViewData["Signer"]!).Rows)
                                {
                                    <option value="@item["Emp_No"]">@item["Emp_Name"]</option>
                                }
                            }
                        </select>
                    </div>
                </div>
            </div>
            @*事由 *@
            <div class="row my-4 mx-4">
                <label for="Leave_Content" class="col-md-1 col-form-label text-end form-label"><span style="color:red">*</span> 事由</label>
                <div class="col-md-10">
                    <textarea class="form-control" asp-for="Leave_Content" id="Leave_Content" required name="Leave_Content" rows="4" placeholder="請輸入請假事由"></textarea>
                </div>
            </div>
            @*按鈕元件 *@
            <div class="col-12 d-md-flex justify-content-md-between">
                <div class="d-grid gap-2 d-md-flex">
                    <button asp-page-handler="Add" class="btn btn-outline-primary">新增</button>
                    <button asp-page-handler="Search" class="btn btn-outline-secondary" >查詢</button>
                    <button asp-page-handler="Updated" class="btn btn-outline-success">更新</button>
                    <button asp-page-handler="Delete" class="btn btn-outline-danger" >刪除</button>
                </div>
                <div class="d-grid gap-2">
                    <button asp-page-handler="Send" class="btn btn-primary">提交</button>
                </div>
            </div>
            <hr style="margin:20px;" />

            @*顯示列表 *@
            <table class="row leave_result">
                <thead>
                    <tr class="d-flex align-items-center py-2" style="background-color:gainsboro;border-radius:3px">
                        <th class ="col-1 text-center">
                            <label for="selectAll">全選</label>
                        <input type="checkbox" id="selectAll"/>
                        </th>
                        <th class="col-2 text-center">單號</th>
                        <th class="col-1 text-center">假別</th>
                        <th class="col-4 text-center">時間</th>
                        <th class="col-2">事由</th>
                        <th class="col-1 text-center">狀態</th>
                        <th class="col-1 text-center">簽核人</th>
                    </tr>
                </thead>
                <tbody>
                    @if (ViewData["QueryLeaveData"] != null)
                    {

                        @foreach (DataRow item in ((DataTable)ViewData["QueryLeaveData"]!).Rows)
                        {
                            <tr class="d-flex align-items-center" style="border-bottom:1px solid lightgrey">
                                <td class="col-1 text-center">
                                    <input type="checkbox" name="selectedItems" class="select-checkbox" value="@item["Leave_No"]" />
                                </td>
                                <td class="col-2 text-center">
                                    @* <a href="#" class="leave-no-link" data-leave-no="@item["Leave_No"]"> @item["Leave_No"] </a> *@
                                    <a data-leave-no="@item["Leave_No"]" asp-page-handler="Edit" asp-route-leaveNo="@item["Leave_No"]">@item["Leave_No"]</a>
                                </td>
                                <td class="col-1 text-center">@item["LeaveName"]</td>
                                <td class="col-4 text-center">@item["Start_Date"]<br />@item["End_Date"]</td>
                                <td class="col-2" style="max-width: 190px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">@item["Leave_Content"]</td>
                                <td class="col-1 text-center">@item["StatusName"]</td>
                                <td class="col-1 text-center">@item["SignNo"]</td>
                            </tr>
                        }
                    }
                </tbody>

            </table>
            

        </div>
    </form>

    <script>
        document.addEventListener('DOMContentLoaded', async function () {
            // 頁面載入時先執行一次計算
            await calculateTimeOnLoad();

            // 添加事件監聽器
            document.getElementById('Start_Date').addEventListener('change', calculateTime);
            document.getElementById('End_Date').addEventListener('change', calculateTime);

            async function calculateTimeOnLoad() {
                // 取得當前的起始日期和結束日期
                var startDate = new Date(document.getElementById('Start_Date').value);
                var endDate = new Date(document.getElementById('End_Date').value);

                // 呼叫計算函數
                await calculateTime(startDate, endDate);
            }

            async function calculateTime() {
                // 取得當前的起始日期和結束日期
                var startDate = new Date(document.getElementById('Start_Date').value);
                var endDate = new Date(document.getElementById('End_Date').value);

                // ajax call to server
                // nan check
                if (isNaN(startDate) || isNaN(endDate) || endDate < startDate) {
                    var hoursElement = document.getElementById('Hours');
                    hoursElement.innerText = '請選擇有效的日期範圍';
                    hoursElement.style.color = 'red';
                    return;
                } else {
                    var hoursElement = document.getElementById('Hours');
                    hoursElement.style.color = '';
                }

                // call api (fetch)
                var response = await fetch('@Url.Page("", "CalculateTime")', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'RequestVerificationToken': '@antiForgery'
                    },
                    body: JSON.stringify({
                        startDate: startDate,
                        endDate: endDate
                    })
                });

                // get response
                var result = await response.json();

                // update UI
                if (result.success) {
                    var hoursElement = document.getElementById('Hours');
                    hoursElement.innerText = result.days + '天' + result.hours + '小時';
                    console.log(result.days, result.hours);
                } else {
                    var hoursElement = document.getElementById('Hours');
                    hoursElement.innerText = result.message;
                    hoursElement.style.color = 'red';
                }
            }
        });

        // 添加事件監聽器
        document.getElementById('selectAll').addEventListener('change', function () {
            var checkboxes = document.querySelectorAll('.select-checkbox');
            checkboxes.forEach(function (checkbox) {
                checkbox.checked = document.getElementById('selectAll').checked;
            });

            // 更新選中的項目
            updateSelectedIds();
        });

        // 添加事件監聽器
        var checkboxes = document.querySelectorAll('.select-checkbox');
        checkboxes.forEach(function (checkbox) {
            checkbox.addEventListener('change', function () {
                updateSelectedIds();
            });
        });

        function updateSelectedIds() {
            var selectedIds = [];
            var checkboxes = document.querySelectorAll('.select-checkbox:checked');
            checkboxes.forEach(function (checkbox) {
                selectedIds.push(checkbox.value);
            });

        }
    </script>
</body>
